### ISSUE TITLE
Annotation auto_update_time is not working properly

### ISSUE THREAD

**Issue by CrsiX** [myOmikron/drorm#41]
Consider a model with the following fields:

```rust
#[derive(Model, Debug)]
pub struct Test {
    #[rorm(id)]
    pub id: i64,

    #[rorm(auto_create_time, auto_update_time)]
    pub updated_at: chrono::NaiveDateTime,
}
```

Then, the generated `.models.json` contains the following snippet:

```json
        {
          "Name": "updated_at",
          "Type": "datetime",
          "Annotations": [
            {
              "Type": "auto_create_time"
            },
            {
              "Type": "auto_create_time"
            },
            {
              "Type": "not_null"
            }
          ]
        }
```

Later, using `rorm-cli` creates the following migration file snippet:

```toml
[[Migration.Operations.Fields]]
Name = "updated_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"
```

But applying this migration fails (here in PostgreSQL). The output is:

```
Error: error returned from database: multiple default values specified for column "updated_at" of table "test"

Caused by:
    multiple default values specified for column "updated_at" of table "test"
```

Since the produced SQL is:

```sql
CREATE TABLE "test" ("id" bigserial PRIMARY KEY , "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 
```
